### ISSUE TITLE
The data can't load successful

### ISSUE THREAD

**Issue by Like-wind-fly** [isbrycee/T-Mamba#2]
Complete the initialization of configuration
/mnt/fourT/cyj/cj/segmentation_teeth_3d/CBCT_data
id: 0
/mnt/fourT/cyj/cj/segmentation_teeth_3d/CBCT_data/segmentation/segmentation-1002165246_20180106.nii.gz

The data loading setback, only load one data without updating further

Waiting for your reply.

**Comment by isjinghao** [comment]
You could show your detailed errors here so I can help you solve your problems

**Comment by Like-wind-fly** [comment]
I have solved, thank  you very much, because the value of "crop_threshold" too high, traped in invalid loop.
 I find the 2-class segmentation result with AttentionUNet3D is bad , tooth roi not localized. How to setting in multi-class segmentation task?

![image](https://github.com/isbrycee/T-Mamba/assets/148784519/d584a83d-f8a5-4295-b70f-3734fe31b660)

**Comment by isjinghao** [comment]
If your task has three or above classes, you can change here when training your models:
https://github.com/isbrycee/T-Mamba/blob/main/train.py#L61

You can try our T-Mamba architecture, because we verified that T-Mamba outperforms AttentionUNet3D by a large margin.

**Comment by Like-wind-fly** [comment]
> If your task has three or above classes, you can change here when training your models: https://github.com/isbrycee/T-Mamba/blob/main/train.py#L61
> 
> You can try our T-Mamba architecture, because we verified that T-Mamba outperforms AttentionUNet3D by a large margin.
ok, Thank you, I will try.
