### ISSUE TITLE
数据集和预训练权重未发布？

### ISSUE THREAD

**Issue by linmeon** [isbrycee/T-Mamba#3]
Hi, isbrycee ,我想尝试使用你的工作来测试分割效果，但是没有看到代码中提到的3D-CBCT-Tooth 这个数据集和 示例的checkpoint，是还没有发布还是在某些地方我没有找到？

**Comment by isjinghao** [comment]
The checkpoint is coming soon. We have been upgrading the T-Mamba for both tooth 2D and 3D modality data.

**Comment by isjinghao** [comment]
> Hi, isbrycee ,我想尝试使用你的工作来测试分割效果，但是没有看到代码中提到的3D-CBCT-Tooth 这个数据集和 示例的checkpoint，是还没有发布还是在某些地方我没有找到？

您好，TED3 数据集已经 released，欢迎下载使用。
