### ISSUE TITLE
RuntimeError: cuFFT only supports dimensions whose sizes are powers of two when computing in half precision, but got a signal size of[48, 262144]

### ISSUE THREAD

**Issue by wakakaFF** [isbrycee/T-Mamba#4]
你好，
我在调试模型的时候可以跑通，但是在训练模型的时候就出现了这个错误，请问这是什么原因导致的呢？
![image](https://github.com/user-attachments/assets/5315780d-f616-499b-906f-113e7d2399d8)

**Comment by isjinghao** [comment]
您好，我查了下是数据类型的问题。fft 不支持半精度计算。

**Comment by wakakaFF** [comment]
是的，感谢你的恢复。我通过在mamba_simple_fft里加上了这行代码，已经解决了。
![1724821190182](https://github.com/user-attachments/assets/fd7fcf87-c5bf-4d82-8361-0940be443cd8)

**Comment by wakakaFF** [comment]
是的，感谢您的回复。我在mamba_simple_fft.py里加上这行代码后，已经可以运行了。
![1724821190182](https://github.com/user-attachments/assets/080ddc22-06a7-4e99-a08b-daf50ae2dbaf)
