### ISSUE TITLE
模型已经训练出来了，运行./infer_3d.sh脚本推理，为啥没有预测的文件生成。

### ISSUE THREAD

**Issue by Qianxunha** [isbrycee/T-Mamba#6]
您好，模型已经训练出来了，运行./infer_3d.sh脚本推理，看了interence.py文件，程序执行完没有预测文件生成，只有xxx.npy文件。
![image](https://github.com/user-attachments/assets/be7d7c68-8dbb-4639-9895-f71b5a1581e7)

![image](https://github.com/user-attachments/assets/7e800264-2224-4b9a-b6c5-05239dcf3fc2)

**Comment by isjinghao** [comment]
您好，xxx.npy 文件就是预测结果文件的 mask，可以将其可视化到您的数据集图像上就好啦～

**Comment by Qianxunha** [comment]
> 您好，xxx.npy 文件就是预测结果文件的 mask，可以将其可视化到您的数据集图像上就好啦～

感谢您的回复，转换ok了，谢谢！
